### ISSUE TITLE
PBS5: Confusing html tags in URL example - possible formatting error?

### ISSUE THREAD

**Issue by steinbil** [bartificer/programming-by-stealth#31]
Are these `<ul>` tags supposed to be visible in the example of how a URL is composed? If they are, I don't understand why from the context. Is this some formatting gone wrong? 

<img width="547" alt="Skjermbilde 2022-06-04 kl  23 43 24" src="https://user-images.githubusercontent.com/6885924/172026358-4c3dc797-5c7e-4bd8-97ca-7ee1e2e6f30b.png">

**Comment by steinbil** [comment]
At first I thought the problem was that the `<li>` tags inside the `<ul>` were missing, but since this is inside a `<code>` tag it wouldn't render as a list anyways..?

**Comment by NosillaCast** [comment]
I'm assigning this one to @hepabolu because I'm not sure how to fix it. In the Markdown preview in Visual Studio Code, it doesn't look like what it does on the web at pbs.bartificer.net. it's supposed to look like this:

<img width="531" alt="CleanShot 2022-06-04 at 18 30 33@2x" src="https://user-images.githubusercontent.com/12651464/172031084-2ab89ccb-bed0-4e7d-b6d1-27451d4f187e.png">
